### ISSUE TITLE
clementviolet - W10D7-5k Race

### ISSUE THREAD

**Issue by ColinFay** [ColinFay/ur-first-5k#414]
Hey @clementviolet, here is W10D7-5k Race:

RACE DAY! GOOD LUCK!

**Comment by clementviolet** [comment]
Done yesterday :tada: :confetti_ball: ! 

[https://www.strava.com/activities/4943569255](https://www.strava.com/activities/4943569255)

Thanks for the coaching  @ColinFay  and  helping me create my running habit. I now enjoy running, something I thought impossible a few months ago. I will continue to train and I will aim for the 10, 15 and 20km 🏃

**Comment by ColinFay** [comment]
Super ! So glad to hear that :) and congratulations 🍾🎈🎉🎊 

Happy to hear that I've converted another R lover to the wonderful world of running 🏃‍♂️
